### ISSUE TITLE
Error: Unexpected token END OF FILE at position 0.

### ISSUE THREAD

**Issue by moda84** [Twi5TeD/PlayTime#17]
[09:36:11 WARN]:  Unexpected token END OF FILE at position 0.
[09:36:11 WARN]: 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
[09:36:11 WARN]: 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:92)
[09:36:11 WARN]: 	at PlayTime.jar//me.F64.PlayTime.Main.writePlayer(Main.java:163)
[09:36:11 WARN]: 	at PlayTime.jar//me.F64.PlayTime.Main.savePlayer(Main.java:122)
[09:36:11 WARN]: 	at PlayTime.jar//me.F64.PlayTime.Main.onPlayerQuit(Main.java:76)
[09:36:11 WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor34.execute(Unknown Source)
[09:36:11 WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[09:36:11 WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[09:36:11 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[09:36:11 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[09:36:11 WARN]: 	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:606)
[09:36:11 WARN]: 	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:591)
[09:36:11 WARN]: 	at net.minecraft.server.network.PlayerConnection.onDisconnect(PlayerConnection.java:1973)
[09:36:11 WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1953)
[09:36:11 WARN]: 	at net.minecraft.network.NetworkManager.m(NetworkManager.java:714)
[09:36:11 WARN]: 	at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:221)
[09:36:11 WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1636)
[09:36:11 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
[09:36:11 WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470)
[09:36:11 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
[09:36:11 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[09:36:11 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
Version: 1.18.1 Paper
I deleted the config, but the error remained

**Comment by Twi5TeD** [comment]
Delete userdata.json in playtime folder and let it regenerate
