### ISSUE TITLE
console error with player disconnect

### ISSUE THREAD

**Issue by t4ba** [Twi5TeD/PlayTime#24]
[14:38:41 WARN]: Unexpected token END OF FILE at position 0.
[14:38:41 WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
[14:38:41 WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.java:92)
[14:38:41 WARN]:        at PlayTime.jar//me.F64.PlayTime.Commands.PlaytimeTop.getTopTen(PlaytimeTop.java:64)
[14:38:41 WARN]:        at PlayTime.jar//me.F64.PlayTime.PlaceholderAPI.Expansion.get(Expansion.java:59)
[14:38:41 WARN]:        at PlayTime.jar//me.F64.PlayTime.PlaceholderAPI.Expansion.onPlaceholderRequest(Expansion.java:95)
[14:38:41 WARN]:        at PlaceholderAPI-2.11.3-DEV-160.jar//me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:32)
[14:38:41 WARN]:        at PlaceholderAPI-2.11.3-DEV-160.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[14:38:41 WARN]:        at PlaceholderAPI-2.11.3-DEV-160.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[14:38:41 WARN]:        at PlaceholderAPI-2.11.3-DEV-160.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
[14:38:41 WARN]:        at DecentHolograms-2.5.2.jar//eu.decentsoftware.holograms.api.utils.PAPI.setPlaceholders(PAPI.java:25)
[14:38:41 WARN]:        at DecentHolograms-2.5.2.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.parsePlaceholders(HologramLine.java:314)
[14:38:41 WARN]:        at DecentHolograms-2.5.2.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.getText(HologramLine.java:284)
[14:38:41 WARN]:        at DecentHolograms-2.5.2.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.update(HologramLine.java:396)
[14:38:41 WARN]:        at DecentHolograms-2.5.2.jar//eu.decentsoftware.holograms.api.holograms.Hologram.lambda$update$5(Hologram.java:401)
[14:38:41 WARN]:        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
[14:38:41 WARN]:        at DecentHolograms-2.5.2.jar//eu.decentsoftware.holograms.api.holograms.Hologram.update(Hologram.java:401)
[14:38:41 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[14:38:41 WARN]:        at DecentHolograms-2.5.2.jar//eu.decentsoftware.holograms.api.holograms.Hologram.updateAll(Hologram.java:407)
[14:38:41 WARN]:        at DecentHolograms-2.5.2.jar//eu.decentsoftware.holograms.api.holograms.Hologram.tick(Hologram.java:222)
[14:38:41 WARN]:        at DecentHolograms-2.5.2.jar//eu.decentsoftware.holograms.api.utils.tick.Ticker.lambda$tick$1(Ticker.java:79)
[14:38:41 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[14:38:41 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[14:38:41 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[14:38:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Twi5TeD** [comment]
change your hologram plugin ive not had any issues with holographic display using it.
