### ISSUE TITLE
Unexpected token RIGHT BRACE(}) at position 65030

### ISSUE THREAD

**Issue by Danila767** [Twi5TeD/PlayTime#31]
When a player logs out of the server:

[13:44:59 WARN]: Unexpected token RIGHT BRACE(}) at position 65030.

[13:44:59 WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.java:146)

[13:44:59 WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.java:92)

[13:44:59 WARN]:        at PlayTime-3.6.jar//me.f64.playtime.Main.writePlayer(Main.java:164)

[13:44:59 WARN]:        at PlayTime-3.6.jar//me.f64.playtime.Main.lambda$savePlayer$3(Main.java:150)

[13:44:59 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)

[13:44:59 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)

[13:44:59 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)

[13:44:59 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)

[13:44:59 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)

[13:44:59 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Twi5TeD** [comment]
currently not found a perm fix for this but for now delete the userdata.json file in the playtime folder
