### ISSUE TITLE
Playtime Top

### ISSUE THREAD

**Issue by sandrpp** [Twi5TeD/PlayTime#32]
When i want to see the Top playtimes with /playtime top I get this Error:
`[21:59:40 WARN]: Unexpected token VALUE(5) at position 12349.
[21:59:40 WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.java:146)
[21:59:40 WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.java:92)
[21:59:40 WARN]:        at PlayTime-3.6 (2).jar//me.f64.playtime.commands.Playtime.getTopTen(Playtime.java:119)
[21:59:40 WARN]:        at PlayTime-3.6 (2).jar//me.f64.playtime.commands.Playtime.onCommand(Playtime.java:187)
[21:59:40 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[21:59:40 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[21:59:40 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:929)
[21:59:40 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[21:59:40 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[21:59:40 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:313)
[21:59:40 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:297)
[21:59:40 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2291)
[21:59:40 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2253)
[21:59:40 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[21:59:40 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
[21:59:40 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[21:59:40 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[21:59:40 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[21:59:40 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1343)
[21:59:40 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[21:59:40 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[21:59:40 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1320)
[21:59:40 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1313)
[21:59:40 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[21:59:40 WARN]:        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1291)
[21:59:40 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1179)
[21:59:40 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[21:59:40 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by Twi5TeD** [comment]
At the moment just stop the server and delete the user data file inside of the playtime folder it will fix the issue for now
