### ISSUE TITLE
PlayTime plugin is giving console error when player is leaving server.

### ISSUE THREAD

**Issue by ys050505** [Twi5TeD/PlayTime#36]
[06:42:23 INFO]: [✖] raistar245
[06:42:23 WARN]: Unexpected token RIGHT BRACE(}) at position 57615.
[06:42:23 WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.java:146)
[06:42:23 WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.java:92)
[06:42:23 WARN]:        at PlayTime-3.6.jar//me.f64.playtime.Main.writePlayer(Main.java:164)
[06:42:23 WARN]:        at PlayTime-3.6.jar//me.f64.playtime.Main.lambda$savePlayer$3(Main.java:150)
[06:42:23 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[06:42:23 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[06:42:23 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[06:42:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[06:42:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[06:42:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

Here is the error 
I am using Minecraft Version 1.19.2
And PlayTime plugin version is 3.6

Please respond me as soon as possible.

**Comment by MrBacon1-1** [comment]
I have the same problem
