### ISSUE TITLE
How to fix this

### ISSUE THREAD

**Issue by DangLeDZ** [Twi5TeD/PlayTime#42]
[17:17:12 WARN]: Unexpected token VALUE(2) at position 8605.
[17:17:12 WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.java:146)
[17:17:12 WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.java:92)
[17:17:12 WARN]:        at PlayTime-3.6.jar//me.f64.playtime.Main.writePlayer(Main.java:164)
[17:17:12 WARN]:        at PlayTime-3.6.jar//me.f64.playtime.Main.lambda$savePlayer$3(Main.java:150)
[17:17:12 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
[17:17:12 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[17:17:12 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:17:12 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:17:12 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:17:12 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by PetyXbron** [comment]
@DangLeDZ it is (the only one?) a very common problem of this plugin.
#### **To fix it, simply, follow [my guide](https://github.com/Twi5TeD/PlayTime/issues/41#issuecomment-1606155483) on issue #41.**
